version: "3"

services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile"
    platform: linux/amd64
    volumes:
      - type: bind
        source: ./extension/
        target: /home/local/
    stdin_open: true
    tty: true
